const fs = require("fs");
const path = require("path");
const { findWorkbook, readWorkbookRecords } = require("./xlsxReader");

/**
 * Syncs one workbook into one generated src/data file. Used by scripts/sync-data.js,
 * which registers every workbook -> generated-file pairing in one place.
 *
 * @param {string} root - project root (path.resolve(__dirname, ".."))
 * @param {object} source
 * @param {string} source.key - short id used for logging and CLI filtering (e.g. "organizations")
 * @param {string[]} source.candidateNames - workbook filenames to look for in data-sources/
 * @param {string} source.outputPath - output file path, relative to root (e.g. "src/data/generatedEvents.js")
 * @param {string} source.outputVarName - exported const name in the generated file
 * @param {(record: object) => boolean} source.filter - keep only rows with the required fields
 * @param {(record: object, index: number) => object} source.map - raw parsed row -> generated record
 */
function syncWorkbook(root, source) {
  const { key, candidateNames, outputPath, outputVarName, filter, map } = source;
  const dataSourcesDir = path.join(root, "data-sources");
  const workbookPath = findWorkbook(dataSourcesDir, candidateNames);
  const absoluteOutputPath = path.join(root, outputPath);

  if (!workbookPath) {
    console.log(`[${key}] No workbook found (looked for ${candidateNames.join(", ")}). Keeping generated data as-is.`);
    return;
  }

  const rows = readWorkbookRecords(workbookPath).filter(filter).map(map);
  const relativeSource = path.relative(root, workbookPath).split(path.sep).join("/");

  const output =
    `// This file is generated by scripts/sync-data.js from ${relativeSource}.\n` +
    "// Edit the workbook, then run npm start or npm run build to refresh it.\n\n" +
    `export const ${outputVarName} = ${JSON.stringify(rows, null, 2)};\n`;

  if (fs.existsSync(absoluteOutputPath) && fs.readFileSync(absoluteOutputPath, "utf8") === output) {
    console.log(`[${key}] Already current for ${rows.length} records.`);
  } else {
    fs.mkdirSync(path.dirname(absoluteOutputPath), { recursive: true });
    fs.writeFileSync(absoluteOutputPath, output);
    console.log(`[${key}] Synced ${rows.length} records from ${path.basename(workbookPath)}.`);
  }
}

module.exports = { syncWorkbook };
